/* Ortaokulluyuz Matematik — tek uygulama dosyası. Aynı cookie, DB ve Google auth altyapısını kullanır. */
(function(){
  const CODES={
    ping:'a0',oturum:'a1',google:'a7',yapilandirma:'a8',cikis:'a9',sorular:'a12',soruEkle:'a13',kisiler:'a27',mesajlar:'a29',mesajGonder:'a2a',istatistik:'a11',
    matOzet:'b1',matEvent:'b2',matAI:'b3',matAdmin:'b4'
  };
  const Api={
    async call(code,data={}){
      const payload={a:code,d:data,t:Date.now(),n:(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random())};
      const r=await fetch('../api/gateway',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload)});
      const txt=await r.text(); let j={}; try{j=txt?JSON.parse(txt):{}}catch(e){j={ok:false,hata:'Sunucudan geçersiz yanıt alındı.'}}; return j;
    },
    async session(){return this.call(CODES.oturum)},
    async config(){return this.call(CODES.yapilandirma)},
    async stats(){return this.call(CODES.matOzet)},
    async event(anahtar,artis=1){return this.call(CODES.matEvent,{anahtar,artis})},
    async ai(payload){return this.call(CODES.matAI,payload)},
    async questions(grade){return this.call(CODES.sorular,{ders:'matematik',sinif:grade||''})},
    async question(payload){return this.call(CODES.soruEkle,{...payload,ders:'matematik'})},
    async people(){return this.call(CODES.kisiler)},
    async messages(id){return this.call(CODES.mesajlar,{karsi_id:id})},
    async sendMessage(id,text){return this.call(CODES.mesajGonder,{alici_id:id,metin:text})},
    async admin(){return this.call(CODES.matAdmin)},
    async logout(){return this.call(CODES.cikis)}
  };
  const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
  const state={user:null,grade:6,aiMode:'one',img:null,aiResult:'',pi:'3.',selectedPerson:null,geo:{tool:'select',start:null,shapes:[]}};
  const topics={
    5:['Doğal Sayılar','Kesirler ve Ondalık Gösterim','Geometri: Temel Kavramlar','Veri Toplama ve Değerlendirme','Uzunluk ve Zaman Ölçme','Alan Ölçme'],
    6:['Doğal Sayılarla İşlemler','Çarpanlar ve Katlar','Tam Sayılar','Cebirsel İfadeler','Oran','Geometri ve Ölçme'],
    7:['Tam Sayılarla İşlemler','Rasyonel Sayılar','Cebirsel İfadeler ve Eşitlik','Oran-Orantı ve Yüzdeler','Doğrular ve Açılar','Çember ve Daire'],
    8:['Çarpanlar ve Katlar / Üslü İfadeler','Kareköklü İfadeler','Veri Analizi ve Olasılık','Cebirsel İfadeler ve Özdeşlikler','Doğrusal Denklemler','Geometrik Cisimler ve Dönüşümler']
  };
  const qtopics=topics;
  function setSelect(id,arr){const e=document.getElementById(id);if(!e)return;e.innerHTML=arr.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}
  function scrollTo(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})}
  function updateTopicSelects(){setSelect('ai-topic',topics[Number(document.getElementById('ai-grade')?.value)||6]);setSelect('q-topic',qtopics[Number(document.getElementById('q-grade')?.value)||6]);}
  async function init(){
    updateTopicSelects();
    document.getElementById('ai-grade')?.addEventListener('change',updateTopicSelects);
    document.getElementById('q-grade')?.addEventListener('change',updateTopicSelects);
    document.getElementById('ai-image')?.addEventListener('change',handleImage);
    document.getElementById('calc-grade')?.addEventListener('change',()=>document.getElementById('calc-topic-badge').textContent=document.getElementById('calc-grade').value+'. sınıf');
    document.querySelectorAll('[data-k]').forEach(b=>b.addEventListener('click',()=>appendCalc(b.dataset.k)));
    setupGeo();
    await loadSession();
    if(document.body.querySelector('#math-questions')) loadQuestions();
    if(location.pathname.endsWith('/mesajlar.html')) MathMessages.init();
    if(location.pathname.endsWith('/yonetim.html')) MathAdmin.init();
    MathApp.refreshStats();
  }
  async function loadSession(){
    const j=await Api.session().catch(()=>null); state.user=j?.ok?j.kullanici:null; renderAccount();
    if(!state.user){
      if(location.pathname.endsWith('/mesajlar.html')||location.pathname.endsWith('/yonetim.html')) location.href='../giris.html?donus=matematik/'+location.pathname.split('/').pop();
    }
  }
  function renderAccount(){const e=document.getElementById('math-account'); if(!e)return; if(!state.user){e.innerHTML='<a class="account-chip" href="../giris.html?donus=matematik/">Giriş yap ↗</a>';return;} const av=state.user.avatar?`<img class="avatar" src="${esc(state.user.avatar)}" alt="">`:`<span class="avatar">${esc(String(state.user.ad||'?')[0].toUpperCase())}</span>`;e.innerHTML=`<div class="account-chip">${av}<div class="account-text"><b>${esc(state.user.ad)}</b><span>${esc(state.user.rol||'ogrenci')}</span></div><a href="../profil.html">Profil</a>${state.user.rol==='admin'?'<a href="yonetim.html">Yönetim</a>':''}<button onclick="MathApp.logout()">Çıkış</button></div>`}
  async function logout(){await Api.logout().catch(()=>{});location.href='../index.html'}
  function sinifSet(s){state.grade=s;document.getElementById('ai-grade').value=String(s);document.getElementById('q-grade').value=String(s);document.getElementById('calc-grade').value=String(s);updateTopicSelects();document.getElementById('calc-topic-badge').textContent=s+'. sınıf';scrollTo('reader');Api.event('sinif_secim')}
  function handleImage(ev){const f=ev.target.files?.[0];if(!f)return;if(!/^image\/(png|jpeg|webp)$/i.test(f.type)||f.size>2*1024*1024){showAIStatus('PNG/JPG/WebP ve 2 MB sınırı.');return}const rd=new FileReader();rd.onload=()=>{state.img=rd.result;const p=document.getElementById('ai-preview');p.src=rd.result;p.classList.remove('hidden');document.getElementById('reader-empty').classList.add('hidden');document.getElementById('ai-selector').classList.remove('hidden');};rd.readAsDataURL(f)}
  function aiMode(btn,mode){state.aiMode=mode;document.querySelectorAll('.selector-btn').forEach(x=>x.classList.toggle('active',x===btn));}
  function showAIStatus(t){const e=document.getElementById('ai-status');if(e)e.textContent=t}
  async function analyzeImage(){if(!state.user){location.href='../giris.html?donus=matematik/';return}if(!state.img){showAIStatus('Önce bir görsel seç.');return}const grade=Number(document.getElementById('ai-grade').value);const topic=document.getElementById('ai-topic').value;const prompt=document.getElementById('ai-prompt').value.trim()||'Soruyu ortaokul öğrencisinin anlayacağı şekilde adım adım çöz. Hesabı kontrol et ve en sonda net cevabı ver.';showAIStatus('AI görseli inceliyor…');document.getElementById('ai-result').textContent='Çözüm hazırlanıyor…';const t=performance.now();const j=await Api.ai({mod:state.aiMode,sinif:grade,konu:topic,prompt,gorsel:state.img});if(j.ok){document.getElementById('ai-result').textContent=j.cevap||'AI yanıt üretmedi.';state.aiResult=j.cevap||'';showAIStatus('Hazır.');await Api.event('ai_analiz');}else{document.getElementById('ai-result').textContent=j.hata||'AI isteği başarısız.';showAIStatus(j.hata||'AI isteği başarısız.')}const ms=Math.round(performance.now()-t);void ms;refreshStats()}
  function clearReader(){state.img=null;document.getElementById('ai-image').value='';document.getElementById('ai-preview').classList.add('hidden');document.getElementById('reader-empty').classList.remove('hidden');document.getElementById('ai-selector').classList.add('hidden');document.getElementById('ai-result').textContent='Bir görsel yükleyip çözüm isteyin.';showAIStatus('AI anahtarı Vercel’de tanımlıysa aktif olur.')}
  async function copyResult(){await navigator.clipboard?.writeText(state.aiResult||document.getElementById('ai-result').textContent||'');}
  function tokenize(s){const out=[];let i=0;while(i<s.length){if(/\s/.test(s[i])){i++;continue}const num=s.slice(i).match(/^(?:\d+(?:\.\d*)?|\.\d+)/);if(num){out.push({t:'num',v:Number(num[0])});i+=num[0].length;continue}const op=s[i];if('+-*/^()%'.includes(op)||op==='('||op===')'){out.push({t:'op',v:op});i++;continue}if(s.slice(i).startsWith('sqrt')){out.push({t:'fn',v:'sqrt'});i+=4;continue}if(s.slice(i).startsWith('pi')){out.push({t:'num',v:Math.PI});i+=2;continue}if(s[i]==='√'){out.push({t:'fn',v:'sqrt'});i++;continue}throw new Error('Anlaşılamayan ifade: '+s.slice(i))}return out}
  function calcEval(expr){const ts=tokenize(expr);const prec={'+':1,'-':1,'*':2,'/':2,'^':3,'%':4};const vals=[],ops=[];let prev='start';const apply=()=>{const o=ops.pop();if(o==='sqrt'){vals.push(Math.sqrt(vals.pop()));return}const b=vals.pop(),a=vals.pop();if(o==='+')vals.push(a+b);else if(o==='-')vals.push(a-b);else if(o==='*')vals.push(a*b);else if(o==='/')vals.push(a/b);else if(o==='^')vals.push(a**b);else if(o==='%')vals.push(a/100)};for(let i=0;i<ts.length;i++){const x=ts[i];if(x.t==='num'){vals.push(x.v);prev='num';continue}if(x.v==='('){ops.push(x.v);prev='(' ;continue}if(x.v===')'){while(ops.length&&ops.at(-1)!=='(')apply();if(ops.pop()!=='(')throw Error('Parantez hatası');if(ops.length&&ops.at(-1)==='sqrt')apply();prev='num';continue}if(x.t==='fn'){ops.push(x.v);prev='fn';continue}if(x.v==='-'&&(['start','('].includes(prev))){vals.push(0)}while(ops.length&&ops.at(-1)!=='('&&prec[ops.at(-1)]>=prec[x.v])apply();ops.push(x.v);prev='op'}while(ops.length) {if(ops.at(-1)==='(')throw Error('Parantez hatası');apply()}if(vals.length!==1||!Number.isFinite(vals[0]))throw Error('İşlem sonucu geçersiz.');return vals[0]}
  function calculate(){const expr=document.getElementById('calc-input').value.trim();if(!expr){document.getElementById('calc-result').textContent='Bir işlem gir.';return}try{const v=calcEval(expr);document.getElementById('calc-result').textContent=String(Number.isInteger(v)?v:Number(v.toFixed(12)));const g=Number(document.getElementById('calc-grade').value);const d=document.getElementById('calc-diff').value;document.getElementById('calc-steps').innerHTML=`<div class="step"><b>İfade</b><br>${esc(expr)}</div><div class="step"><b>Seviye</b><br>${g}. sınıf · ${esc(d)}</div><div class="step highlight"><b>Gerçek hesap sonucu</b><br>${esc(Number.isInteger(v)?v:Number(v.toFixed(12)))}</div>`;Api.event('hesap_cozumu')}catch(e){document.getElementById('calc-result').textContent=e.message;document.getElementById('calc-steps').innerHTML=''} }
  function appendCalc(k){const el=document.getElementById('calc-input');if(k==='sqrt')el.value+='√(';else el.value+=k}
  function calcClear(){document.getElementById('calc-input').value='';document.getElementById('calc-result').textContent='Bir işlem gir.';document.getElementById('calc-steps').innerHTML=''}
  function intSqrt(n){if(n<0n)throw Error('neg');if(n<2n)return n;let x0=1n<<(BigInt(n.toString(2).length)+1n>>1n);let x1=(x0+n/x0)>>1n;while(x1<x0){x0=x1;x1=(x0+n/x0)>>1n}return x0}
  async function piStart(){const digits=Math.max(5,Math.min(500,Number(document.getElementById('pi-digits').value)||80));const out=document.getElementById('pi-output');const prog=document.getElementById('pi-progress');const stage=document.getElementById('pi-stage');const steps=document.getElementById('pi-steps');steps.innerHTML='';stage.textContent='Sıfırdan hesaplanıyor…';out.textContent='3.';prog.style.width='0%';await Api.event('pi_baslat');await new Promise(r=>setTimeout(r,30));const guard=8,scale=10n**BigInt(digits+guard);let sum1=0n,sum2=0n;const q1=5n,q2=239n;const terms=Math.ceil((digits+guard)*0.73)+2;for(let n=0;n<terms;n++){const d1=q1**BigInt(2*n+1)*BigInt(2*n+1);const d2=q2**BigInt(2*n+1)*BigInt(2*n+1);const a=scale/d1;const b=scale/d2;sum1 += n%2===0?a:-a;sum2 += n%2===0?b:-b;const pct=Math.min(100,Math.round((n+1)/terms*100));prog.style.width=pct+'%';stage.textContent=`Machin serisi · ${n+1}/${terms} terim`;if(n%3===0)await new Promise(r=>setTimeout(r,0))}const raw=16n*sum1-4n*sum2;const intPart=raw/scale;const frac=(raw%scale).toString().padStart(digits+guard,'0');const answer=intPart+'.'+frac.slice(0,digits);out.textContent=answer;state.pi=answer;stage.textContent=`Tamamlandı · ${digits} basamak`;steps.innerHTML='<span class="pi-step">16 × atan(1/5)</span><span class="pi-step">− 4 × atan(1/239)</span><span class="pi-step">BigInt sabit nokta</span>';await Api.event('pi_hesapla')}
  async function copyPi(){await navigator.clipboard?.writeText(state.pi||'')}
  function setupGeo(){const svg=document.getElementById('geo-svg');if(!svg)return;document.querySelectorAll('.geo-toolbar .tool').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.geo-toolbar .tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.geo.tool=b.dataset.tool;state.geo.start=null}));svg.addEventListener('pointermove',e=>{const p=svgPoint(e,svg);document.getElementById('geo-coord').textContent=`x: ${((p.x-500)/20).toFixed(1)} · y: ${((290-p.y)/20).toFixed(1)}`});svg.addEventListener('pointerdown',e=>{const p=svgPoint(e,svg);if(state.geo.tool==='point'){addCircle(p,4);return}if(state.geo.tool==='select')return;state.geo.start=p;svg.setPointerCapture(e.pointerId)});svg.addEventListener('pointerup',e=>{if(!state.geo.start)return;const p=svgPoint(e,svg);drawShape(state.geo.tool,state.geo.start,p);state.geo.start=null;svg.releasePointerCapture?.(e.pointerId)})}
  function svgPoint(e,svg){const r=svg.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*1000,y:(e.clientY-r.top)/r.height*580}}
  function drawShape(tool,a,b){const g=document.getElementById('geo-shapes');let el;const ns='http://www.w3.org/2000/svg';const attrs={fill:'none',stroke:'#315ee7','stroke-width':'4'};if(tool==='line'){el=document.createElementNS(ns,'line');Object.assign(el.dataset,{x1:a.x,y1:a.y,x2:b.x,y2:b.y});for(const[k,v]of Object.entries(attrs))el.setAttribute(k,v);el.setAttribute('x1',a.x);el.setAttribute('y1',a.y);el.setAttribute('x2',b.x);el.setAttribute('y2',b.y);const d=Math.hypot(b.x-a.x,b.y-a.y)/20;document.getElementById('geo-measure').textContent=`Uzunluk ≈ ${d.toFixed(2)} birim`}else if(tool==='rect'){el=document.createElementNS(ns,'rect');Object.assign(el.dataset,{x:a.x,y:a.y});for(const[k,v]of Object.entries(attrs))el.setAttribute(k,v);el.setAttribute('x',Math.min(a.x,b.x));el.setAttribute('y',Math.min(a.y,b.y));el.setAttribute('width',Math.abs(b.x-a.x));el.setAttribute('height',Math.abs(b.y-a.y));const ar=Math.abs(b.x-a.x)*Math.abs(b.y-a.y)/400;document.getElementById('geo-measure').textContent=`Alan ≈ ${ar.toFixed(2)} birim²`}else if(tool==='circle'){el=document.createElementNS(ns,'circle');for(const[k,v]of Object.entries(attrs))el.setAttribute(k,v);const r=Math.hypot(b.x-a.x,b.y-a.y);el.setAttribute('cx',a.x);el.setAttribute('cy',a.y);el.setAttribute('r',r);document.getElementById('geo-measure').textContent=`Yarıçap ≈ ${(r/20).toFixed(2)} birim · Çevre ≈ ${(2*Math.PI*r/20).toFixed(2)}`}else if(tool==='ruler'){el=document.createElementNS(ns,'line');for(const[k,v]of Object.entries(attrs))el.setAttribute(k,v);el.setAttribute('stroke','#18a98f');el.setAttribute('x1',a.x);el.setAttribute('y1',a.y);el.setAttribute('x2',b.x);el.setAttribute('y2',b.y);document.getElementById('geo-measure').textContent=`Cetvel ölçümü ≈ ${(Math.hypot(b.x-a.x,b.y-a.y)/20).toFixed(2)} birim`}else if(tool==='angle'){el=document.createElementNS(ns,'path');for(const[k,v]of Object.entries(attrs))el.setAttribute(k,v);const dx=b.x-a.x,dy=b.y-a.y,ang=Math.atan2(dy,dx);const r=56;const x2=a.x+r*Math.cos(ang),y2=a.y+r*Math.sin(ang);const d2=`M ${a.x} ${a.y} L ${a.x+r} ${a.y} A ${r} ${r} 0 0 1 ${x2} ${y2}`;el.setAttribute('d',d2);let deg=Math.abs(ang*180/Math.PI);if(deg<0)deg+=180;document.getElementById('geo-measure').textContent=`Açı ≈ ${deg.toFixed(1)}°`}if(el)g.appendChild(el);Api.event('geometri_araci')}
  function addCircle(p,r){const ns='http://www.w3.org/2000/svg',c=document.createElementNS(ns,'circle');c.setAttribute('cx',p.x);c.setAttribute('cy',p.y);c.setAttribute('r',r);c.setAttribute('fill','#3772ff');document.getElementById('geo-shapes').appendChild(c)}
  function geoClear(){document.getElementById('geo-shapes').innerHTML='';document.getElementById('geo-measure').textContent='Bir araç seç.'}
  async function loadQuestions(){const g=document.getElementById('q-grade')?.value||'';const e=document.getElementById('math-questions');if(!e)return;e.innerHTML='Yükleniyor…';const j=await Api.questions(g);if(!j?.ok){e.textContent=j?.hata||'Sorular alınamadı.';return}e.innerHTML=(j.sorular||[]).slice(0,8).map(x=>`<div class="question-item"><b>${esc(x.baslik)}</b><span>${esc(x.yazar)} · ${esc(x.unite)} · ${x.cozuldu?'Çözüldü':'Açık'}</span><p>${esc(String(x.govde||'').slice(0,170))}</p></div>`).join('')||'<div class="mini-note">Henüz matematik sorusu yok.</div>'}
  async function askQuestion(){if(!state.user){location.href='../giris.html?donus=matematik/';return}const sinif=Number(document.getElementById('q-grade').value),unite=document.getElementById('q-topic').value,baslik=document.getElementById('q-title').value.trim(),govde=document.getElementById('q-body').value.trim();if(baslik.length<8||govde.length<10){document.getElementById('q-status').textContent='Başlık ve açıklama biraz daha detaylı olmalı.';return}const j=await Api.question({sinif,unite,baslik,govde});document.getElementById('q-status').textContent=j.ok?'Sorun ortak forumda yayınlandı.':(j.hata||'Yayınlanamadı.');if(j.ok){document.getElementById('q-title').value='';document.getElementById('q-body').value='';await Api.event('soru_paylasim');loadQuestions()}}
  async function refreshStats(){const j=await Api.stats().catch(()=>null);if(!j?.ok)return;const m=j.metrikler||{};const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=Number(v||0).toLocaleString('tr-TR')};set('math-stat-solve',m.hesap);set('math-stat-ai',m.ai);set('math-stat-q',m.soru);set('math-stat-geo',m.geometri);set('math-stat-pi',m.pi)}
  const MathMessages={
    init:async()=>{await loadSession();if(!state.user)return;await MathMessages.loadPeople()},
    loadPeople:async()=>{const e=document.getElementById('people');if(!e)return;const j=await Api.people();if(!j?.ok){e.textContent=j?.hata||'Kişiler alınamadı.';return}e.innerHTML=(j.kisiler||[]).map(x=>`<div class="person" onclick="MathMessages.open(${Number(x.id)})"><span class="avatar">${x.avatar?`<img class="avatar" src="${esc(x.avatar)}" alt="">`:esc(String(x.ad||'?')[0])}</span><span><b>${esc(x.ad)}</b><small>${esc(x.rol||'ogrenci')}</small></span></div>`).join('')||'<div class="mini-note">Başka kullanıcı yok.</div>'},
    open:async(id)=>{state.selectedPerson=id;const j=await Api.messages(id);if(!j?.ok){document.getElementById('chat-list').textContent=j?.hata||'Sohbet alınamadı.';return}document.getElementById('chat-head').textContent=j.karsi?.ad||'Sohbet';const me=state.user?.id;document.getElementById('chat-list').innerHTML=(j.mesajlar||[]).map(m=>`<div class="msg ${Number(m.gonderen_id)===Number(me)?'me':'them'}">${esc(m.metin)}</div>`).join('')||'<div class="empty-chat">Henüz mesaj yok.</div>'},
    send:async ev=>{ev.preventDefault();if(!state.selectedPerson)return;const input=document.getElementById('chat-input');const text=input.value.trim();if(!text)return;const j=await Api.sendMessage(state.selectedPerson,text);if(j.ok){input.value='';await MathMessages.open(state.selectedPerson)}}
  };
  const MathAdmin={init:async()=>{const j=await Api.call(CODES.matAdmin);if(!j?.ok){document.getElementById('adm-list').textContent=j?.hata||'Yetkisiz';return}const m=j.istatistik||{};const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=Number(v||0).toLocaleString('tr-TR')};set('adm-active',m.aktif);set('adm-ai',m.ai);set('adm-solves',m.hesap);set('adm-q',m.soru);set('adm-geo',m.geometri);set('adm-pi',m.pi);document.getElementById('adm-list').innerHTML=(j.son||[]).map(x=>`<div class="admin-row"><span>${esc(x.ad||'Kullanıcı')}</span><span>AI ${x.ai||0} · Hesap ${x.hesap||0}</span><span>Geo ${x.geometri||0}</span><span>${new Date(x.son_guncelleme).toLocaleString('tr-TR')}</span></div>`).join('')||'Henüz matematik aktivitesi yok.'},load:async function(){await this.init()}};
  window.MathApp={scrollTo,sinifSet,aiMode,analyzeImage,clearReader,copyResult,calculate,calcClear,piStart,copyPi,geoClear,askQuestion,loadQuestions,logout,appendCalc};
  window.MathMessages=MathMessages;window.MathAdmin=MathAdmin;
  document.addEventListener('DOMContentLoaded',init);
})();
