/* Ortaokulluyuz Matematik — tek uygulama dosyası. Aynı cookie, DB ve Google auth altyapısını kullanır. */
(function(){
  const CODES={
    ping:'a0',oturum:'a1',google:'a7',yapilandirma:'a8',cikis:'a9',sorular:'a12',soruEkle:'a13',kisiler:'a27',mesajlar:'a29',mesajGonder:'a2a',istatistik:'a11',
    matOzet:'b1',matEvent:'b2',matAI:'b3',matAdmin:'b4'
  };
  const Api={
    async call(code,data={}){
      const payload={a:code,d:data,t:Date.now(),n:(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random())};
      const r=await fetch('../api/gateway',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload)});
      const txt=await r.text(); let j={}; try{j=txt?JSON.parse(txt):{}}catch(e){j={ok:false,hata:'Sunucudan geçersiz yanıt alındı.'}}; return j;
    },
    async session(){return this.call(CODES.oturum)},
    async config(){return this.call(CODES.yapilandirma)},
    async stats(){return this.call(CODES.matOzet)},
    async event(anahtar,artis=1){return this.call(CODES.matEvent,{anahtar,artis})},
    async ai(payload){return this.call(CODES.matAI,payload)},
    async questions(grade){return this.call(CODES.sorular,{ders:'matematik',sinif:grade||''})},
    async question(payload){return this.call(CODES.soruEkle,{...payload,ders:'matematik'})},
    async people(){return this.call(CODES.kisiler)},
    async messages(id){return this.call(CODES.mesajlar,{karsi_id:id})},
    async sendMessage(id,text){return this.call(CODES.mesajGonder,{alici_id:id,metin:text})},
    async admin(){return this.call(CODES.matAdmin)},
    async logout(){return this.call(CODES.cikis)}
  };
  const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
  const state={user:null,grade:6,aiMode:'one',img:null,aiResult:'',pi:'3.',selectedPerson:null,geo:{tool:'select',start:null,points:[],shapes:[],preview:null}};
  const topics={
    5:['Doğal Sayılar','Kesirler ve Ondalık Gösterim','Geometri: Temel Kavramlar','Veri Toplama ve Değerlendirme','Uzunluk ve Zaman Ölçme','Alan Ölçme'],
    6:['Doğal Sayılarla İşlemler','Çarpanlar ve Katlar','Tam Sayılar','Cebirsel İfadeler','Oran','Geometri ve Ölçme'],
    7:['Tam Sayılarla İşlemler','Rasyonel Sayılar','Cebirsel İfadeler ve Eşitlik','Oran-Orantı ve Yüzdeler','Doğrular ve Açılar','Çember ve Daire'],
    8:['Çarpanlar ve Katlar / Üslü İfadeler','Kareköklü İfadeler','Veri Analizi ve Olasılık','Cebirsel İfadeler ve Özdeşlikler','Doğrusal Denklemler','Geometrik Cisimler ve Dönüşümler']
  };
  const qtopics=topics;
  function setSelect(id,arr){const e=document.getElementById(id);if(!e)return;e.innerHTML=arr.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}
  function scrollTo(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})}
  function updateTopicSelects(){setSelect('ai-topic',topics[Number(document.getElementById('ai-grade')?.value)||6]);setSelect('q-topic',qtopics[Number(document.getElementById('q-grade')?.value)||6]);}
  async function init(){
    updateTopicSelects();
    document.getElementById('ai-grade')?.addEventListener('change',updateTopicSelects);
    document.getElementById('q-grade')?.addEventListener('change',updateTopicSelects);
    document.getElementById('ai-image')?.addEventListener('change',handleImage);
    document.getElementById('calc-grade')?.addEventListener('change',()=>document.getElementById('calc-topic-badge').textContent=document.getElementById('calc-grade').value+'. sınıf');
    document.querySelectorAll('[data-k]').forEach(b=>b.addEventListener('click',()=>appendCalc(b.dataset.k)));
    setupGeo();
    await loadSession();
    if(document.body.querySelector('#math-questions')) loadQuestions();
    if(location.pathname.endsWith('/mesajlar.html')) MathMessages.init();
    if(location.pathname.endsWith('/yonetim.html')) MathAdmin.init();
    MathApp.refreshStats();
  }
  async function loadSession(){
    const j=await Api.session().catch(()=>null); state.user=j?.ok?j.kullanici:null; renderAccount();
    if(!state.user){
      if(location.pathname.endsWith('/mesajlar.html')||location.pathname.endsWith('/yonetim.html')) location.href='../giris.html?donus=matematik/'+location.pathname.split('/').pop();
    }
  }
  function renderAccount(){const e=document.getElementById('math-account'); if(!e)return; if(!state.user){e.innerHTML='<a class="account-chip" href="../giris.html?donus=matematik/">Giriş yap ↗</a>';return;} const av=state.user.avatar?`<img class="avatar" src="${esc(state.user.avatar)}" alt="">`:`<span class="avatar">${esc(String(state.user.ad||'?')[0].toUpperCase())}</span>`;e.innerHTML=`<div class="account-chip">${av}<div class="account-text"><b>${esc(state.user.ad)}</b><span>${esc(state.user.rol||'ogrenci')}</span></div><a href="../profil.html">Profil</a>${state.user.rol==='admin'?'<a href="yonetim.html">Yönetim</a>':''}<button onclick="MathApp.logout()">Çıkış</button></div>`}
  async function logout(){await Api.logout().catch(()=>{});location.href='../index.html'}
  function sinifSet(s){state.grade=s;document.getElementById('ai-grade').value=String(s);document.getElementById('q-grade').value=String(s);document.getElementById('calc-grade').value=String(s);updateTopicSelects();document.getElementById('calc-topic-badge').textContent=s+'. sınıf';scrollTo('reader');Api.event('sinif_secim')}
  function handleImage(ev){const f=ev.target.files?.[0];if(!f)return;if(!/^image\/(png|jpeg|webp)$/i.test(f.type)||f.size>2*1024*1024){showAIStatus('PNG/JPG/WebP ve 2 MB sınırı.');return}const rd=new FileReader();rd.onload=()=>{state.img=rd.result;const p=document.getElementById('ai-preview');p.src=rd.result;p.classList.remove('hidden');document.getElementById('ai-image-stage').classList.remove('hidden');document.getElementById('reader-empty').classList.add('hidden');document.getElementById('ai-selector').classList.remove('hidden');document.getElementById('ai-final-image').removeAttribute('src');document.getElementById('ai-visual-result').classList.add('hidden');};rd.readAsDataURL(f)}
  function aiMode(btn,mode){state.aiMode=mode;document.querySelectorAll('.selector-btn').forEach(x=>x.classList.toggle('active',x===btn));}
  function showAIStatus(t){const e=document.getElementById('ai-status');if(e)e.textContent=t}
  function drawAIResult(data){const img=document.getElementById('ai-preview'),canvas=document.getElementById('ai-annotated'),final=document.getElementById('ai-final-image');if(!img||!canvas)return;const finish=()=>{canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0);ctx.font=`700 ${Math.max(18,Math.round(img.naturalWidth/45))}px Arial`;ctx.textBaseline='middle';for(const m of (data.isaretlemeler||[])){const x=m.x*canvas.width,y=m.y*canvas.height,w=Math.max(24,m.w*canvas.width),h=Math.max(22,m.h*canvas.height);ctx.lineWidth=Math.max(3,canvas.width/500);ctx.strokeStyle=m.tur==='sik'||m.dogru?'#16a34a':'#315ee7';ctx.fillStyle='rgba(255,255,255,.88)';if(m.tur==='sik'||m.tur==='isaret'){ctx.beginPath();ctx.arc(x+w/2,y+h/2,Math.min(w,h)*.38,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#15803d';ctx.fillText('✓',x+w/2-10,y+h/2)}else{ctx.fillStyle='rgba(255,255,255,.92)';ctx.strokeRect(x,y,w,h);ctx.fillStyle='#183b70';ctx.fillText(m.metin||'',x+8,y+h/2)} }final.src=canvas.toDataURL('image/png');document.getElementById('ai-visual-result').classList.remove('hidden')};if(img.complete&&img.naturalWidth)finish();else img.onload=finish}
  async function analyzeImage(){if(!state.user){location.href='../giris.html?donus=matematik/';return}if(!state.img){showAIStatus('Önce bir görsel seç.');return}const grade=Number(document.getElementById('ai-grade').value);const topic=document.getElementById('ai-topic').value;const prompt=document.getElementById('ai-prompt').value.trim()||'Fotoğraftaki soruyu çöz, doğru cevabı fotoğrafta doğru yere göster ve altta temiz, öğrencinin anlayacağı şekilde adım adım anlat.';showAIStatus('AI fotoğrafı inceliyor ve cevapları fotoğrafın üzerine yerleştiriyor…');document.getElementById('ai-result').textContent='Çözüm hazırlanıyor…';const j=await Api.ai({mod:state.aiMode,sinif:grade,konu:topic,prompt,gorsel:state.img});if(j.ok){state.aiResult=(j.aciklama||j.cevap||'').replace(/[\$`]/g,'');document.getElementById('ai-result').textContent=(j.ozet?j.ozet+'\n\n':'')+state.aiResult;drawAIResult(j);showAIStatus(`${j.bulunan_soru_sayisi||0} soru işlendi.`);await Api.event('ai_analiz');}else{document.getElementById('ai-result').textContent=j.hata||'AI isteği başarısız.';showAIStatus(j.hata||'AI isteği başarısız.')}refreshStats()}
  function clearReader(){state.img=null;document.getElementById('ai-image').value='';document.getElementById('ai-preview').classList.add('hidden');document.getElementById('ai-image-stage').classList.add('hidden');document.getElementById('reader-empty').classList.remove('hidden');document.getElementById('ai-selector').classList.add('hidden');document.getElementById('ai-visual-result').classList.add('hidden');document.getElementById('ai-result').textContent='Bir görsel yükleyip çözüm isteyin.';showAIStatus('Hazır.')}
  async function copyResult(){await navigator.clipboard?.writeText(state.aiResult||document.getElementById('ai-result').textContent||'')}
  function downloadAIImage(){const src=document.getElementById('ai-final-image')?.src;if(!src)return;const a=document.createElement('a');a.href=src;a.download='ortaokulluyuz-matematik-cozulmus.png';a.click()}
  function tokenize(s){const out=[];let i=0;while(i<s.length){if(/\s/.test(s[i])){i++;continue}const num=s.slice(i).match(/^(?:\d+(?:\.\d*)?|\.\d+)/);if(num){out.push({t:'num',v:Number(num[0])});i+=num[0].length;continue}const op=s[i];if('+-*/^()%'.includes(op)||op==='('||op===')'){out.push({t:'op',v:op});i++;continue}if(s.slice(i).startsWith('sqrt')){out.push({t:'fn',v:'sqrt'});i+=4;continue}if(s.slice(i).startsWith('pi')){out.push({t:'num',v:Math.PI});i+=2;continue}if(s[i]==='√'){out.push({t:'fn',v:'sqrt'});i++;continue}throw new Error('Anlaşılamayan ifade: '+s.slice(i))}return out}
  function calcEval(expr){const ts=tokenize(expr);const prec={'+':1,'-':1,'*':2,'/':2,'^':3,'%':4};const vals=[],ops=[];let prev='start';const apply=()=>{const o=ops.pop();if(o==='sqrt'){vals.push(Math.sqrt(vals.pop()));return}const b=vals.pop(),a=vals.pop();if(o==='+')vals.push(a+b);else if(o==='-')vals.push(a-b);else if(o==='*')vals.push(a*b);else if(o==='/')vals.push(a/b);else if(o==='^')vals.push(a**b);else if(o==='%')vals.push(a/100)};for(let i=0;i<ts.length;i++){const x=ts[i];if(x.t==='num'){vals.push(x.v);prev='num';continue}if(x.v==='('){ops.push(x.v);prev='(' ;continue}if(x.v===')'){while(ops.length&&ops.at(-1)!=='(')apply();if(ops.pop()!=='(')throw Error('Parantez hatası');if(ops.length&&ops.at(-1)==='sqrt')apply();prev='num';continue}if(x.t==='fn'){ops.push(x.v);prev='fn';continue}if(x.v==='-'&&(['start','('].includes(prev))){vals.push(0)}while(ops.length&&ops.at(-1)!=='('&&prec[ops.at(-1)]>=prec[x.v])apply();ops.push(x.v);prev='op'}while(ops.length) {if(ops.at(-1)==='(')throw Error('Parantez hatası');apply()}if(vals.length!==1||!Number.isFinite(vals[0]))throw Error('İşlem sonucu geçersiz.');return vals[0]}
  function calculate(){const expr=document.getElementById('calc-input').value.trim();if(!expr){document.getElementById('calc-result').textContent='Bir işlem gir.';return}try{const v=calcEval(expr);document.getElementById('calc-result').textContent=String(Number.isInteger(v)?v:Number(v.toFixed(12)));const g=Number(document.getElementById('calc-grade').value);const d=document.getElementById('calc-diff').value;document.getElementById('calc-steps').innerHTML=`<div class="step"><b>İfade</b><br>${esc(expr)}</div><div class="step"><b>Seviye</b><br>${g}. sınıf · ${esc(d)}</div><div class="step highlight"><b>Gerçek hesap sonucu</b><br>${esc(Number.isInteger(v)?v:Number(v.toFixed(12)))}</div>`;Api.event('hesap_cozumu')}catch(e){document.getElementById('calc-result').textContent=e.message;document.getElementById('calc-steps').innerHTML=''} }
  function appendCalc(k){const el=document.getElementById('calc-input');if(k==='sqrt')el.value+='√(';else el.value+=k}
  function calcClear(){document.getElementById('calc-input').value='';document.getElementById('calc-result').textContent='Bir işlem gir.';document.getElementById('calc-steps').innerHTML=''}
  function intSqrt(n){if(n<0n)throw Error('neg');if(n<2n)return n;let x0=1n<<(BigInt(n.toString(2).length)+1n>>1n);let x1=(x0+n/x0)>>1n;while(x1<x0){x0=x1;x1=(x0+n/x0)>>1n}return x0}
  async function piStart(){const raw=document.getElementById('pi-digits').value.trim();if(!/^\d+$/.test(raw)||BigInt(raw)<5n){document.getElementById('pi-stage').textContent='En az 5 basamak gir.';return}const digits=Number(raw);if(!Number.isSafeInteger(digits)){document.getElementById('pi-stage').textContent='Bu tarayıcıda bu kadar basamak tek seferde sayı olarak işlenemiyor.';return}const out=document.getElementById('pi-output'),prog=document.getElementById('pi-progress'),stage=document.getElementById('pi-stage'),steps=document.getElementById('pi-steps');steps.innerHTML='';out.textContent='Hesaplanıyor…';prog.style.width='0%';await Api.event('pi_baslat');const guard=12,scale=10n**BigInt(digits+guard),terms=Math.ceil((digits+guard)/14)+2;let C=426880n*intSqrt(10005n*scale*scale),M=1n,L=13591409n,X=1n,K=6n,S=13591409n*scale;for(let k=1;k<terms;k++){M=(K**3n-16n*K)*M/(BigInt(k)**3n);L+=545140134n;X*=-262537412640768000n;S+=(M*L*scale)/X;K+=12n;if(k%2===1||k===terms-1){prog.style.width=Math.round(k/(terms-1)*100)+'%';stage.textContent=`Chudnovsky · ${k}/${terms-1} terim`;await new Promise(r=>setTimeout(r,0))}}const piScaled=(C*scale)/S;const rawPi=piScaled.toString().padStart(digits+1,'0');const answer=rawPi.slice(0,1)+'.'+rawPi.slice(1,digits+1);out.textContent=answer;state.pi=answer;stage.textContent=`Tamamlandı · ${digits.toLocaleString('tr-TR')} basamak`;steps.innerHTML='<span class="pi-step">Chudnovsky serisi</span><span class="pi-step">BigInt yüksek hassasiyet</span><span class="pi-step">Yapay 500 basamak sınırı yok</span>';await Api.event('pi_hesapla')}
  async function copyPi(){await navigator.clipboard?.writeText(state.pi||'')}
  function svgPoint(e,svg){const r=svg.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*1000,y:(e.clientY-r.top)/r.height*580}}
  function nearestPoint(p){let best=null,bd=18;for(const q of state.geo.points){const d=Math.hypot(p.x-q.x,p.y-q.y);if(d<bd){best=q;bd=d}}return best}
  function setupGeo(){const svg=document.getElementById('geo-svg');if(!svg)return;document.querySelectorAll('.geo-toolbar .tool').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.geo-toolbar .tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.geo.tool=b.dataset.tool;state.geo.start=null}));svg.addEventListener('pointermove',e=>{const p=svgPoint(e,svg),q=nearestPoint(p);const use=q||p;document.getElementById('geo-coord').textContent=`x: ${((use.x-500)/20).toFixed(2)} · y: ${((290-use.y)/20).toFixed(2)}${q?' · ● nokta yakalandı':''}`});svg.addEventListener('pointerdown',e=>{const raw=svgPoint(e,svg),p=nearestPoint(raw)||raw;if(state.geo.tool==='point'){addPoint(p);return}if(state.geo.tool==='select')return;state.geo.start=p;svg.setPointerCapture(e.pointerId)});svg.addEventListener('pointerup',e=>{if(!state.geo.start)return;const raw=svgPoint(e,svg),p=nearestPoint(raw)||raw;drawShape(state.geo.tool,state.geo.start,p);state.geo.start=null;svg.releasePointerCapture?.(e.pointerId)})}
  function addPoint(p){const id=state.geo.points.length+1;state.geo.points.push({id,x:p.x,y:p.y});const ns='http://www.w3.org/2000/svg',g=document.getElementById('geo-shapes'),c=document.createElementNS(ns,'circle'),t=document.createElementNS(ns,'text');c.setAttribute('cx',p.x);c.setAttribute('cy',p.y);c.setAttribute('r',6);c.setAttribute('fill','#315ee7');c.dataset.point=id;t.setAttribute('x',p.x+10);t.setAttribute('y',p.y-10);t.setAttribute('font-size','16');t.setAttribute('font-weight','700');t.setAttribute('fill','#183b70');t.textContent=String.fromCharCode(64+id);t.dataset.point=id;g.append(c,t);updateGeometry();Api.event('geometri_araci')}
  function lineThrough(a,b,meta=''){const ns='http://www.w3.org/2000/svg',l=document.createElementNS(ns,'line');l.setAttribute('x1',a.x);l.setAttribute('y1',a.y);l.setAttribute('x2',b.x);l.setAttribute('y2',b.y);l.setAttribute('stroke','#315ee7');l.setAttribute('stroke-width','4');l.dataset.auto=meta;document.getElementById('geo-shapes').appendChild(l);return l}
  function angleAt(A,B,C){const ux=A.x-B.x,uy=A.y-B.y,vx=C.x-B.x,vy=C.y-B.y;const dot=ux*vx+uy*vy,den=Math.hypot(ux,uy)*Math.hypot(vx,vy);return Math.acos(Math.max(-1,Math.min(1,dot/den)))*180/Math.PI}
  function updateGeometry(){const pts=state.geo.points;if(pts.length>=2){const a=pts[pts.length-2],b=pts[pts.length-1];lineThrough(a,b,'auto')}if(pts.length>=3){const A=pts[pts.length-3],B=pts[pts.length-2],C=pts[pts.length-1],deg=angleAt(A,B,C);const ns='http://www.w3.org/2000/svg',r=48;const a1=Math.atan2(A.y-B.y,A.x-B.x),a2=Math.atan2(C.y-B.y,C.x-B.x);let diff=a2-a1;while(diff<=-Math.PI)diff+=2*Math.PI;while(diff>Math.PI)diff-=2*Math.PI;const large=Math.abs(diff)>Math.PI?1:0;const sweep=diff>=0?1:0;const arc=document.createElementNS(ns,'path');arc.setAttribute('d',`M ${B.x+r*Math.cos(a1)} ${B.y+r*Math.sin(a1)} A ${r} ${r} 0 ${large} ${sweep} ${B.x+r*Math.cos(a2)} ${B.y+r*Math.sin(a2)}`);arc.setAttribute('fill','none');arc.setAttribute('stroke','#ef7b24');arc.setAttribute('stroke-width','4');document.getElementById('geo-shapes').appendChild(arc);const label=document.createElementNS(ns,'text');label.setAttribute('x',B.x+60*Math.cos(a1+diff/2));label.setAttribute('y',B.y+60*Math.sin(a1+diff/2));label.setAttribute('fill','#c75d0a');label.setAttribute('font-size','16');label.setAttribute('font-weight','800');label.textContent=deg.toFixed(6)+'°';document.getElementById('geo-shapes').appendChild(label);document.getElementById('geo-measure').textContent=`∠${String.fromCharCode(64+A.id)}${String.fromCharCode(64+B.id)}${String.fromCharCode(64+C.id)} = ${deg.toFixed(6)}°`}}
  function drawShape(tool,a,b){const g=document.getElementById('geo-shapes'),ns='http://www.w3.org/2000/svg';if(tool==='line'){const q1=nearestPoint(a)||a,q2=nearestPoint(b)||b;lineThrough(q1,q2);document.getElementById('geo-measure').textContent=`Doğru uzunluğu = ${(Math.hypot(q2.x-q1.x,q2.y-q1.y)/20).toFixed(6)} birim`}else if(tool==='rect'){const r=document.createElementNS(ns,'rect');r.setAttribute('x',Math.min(a.x,b.x));r.setAttribute('y',Math.min(a.y,b.y));r.setAttribute('width',Math.abs(b.x-a.x));r.setAttribute('height',Math.abs(b.y-a.y));r.setAttribute('fill','none');r.setAttribute('stroke','#315ee7');r.setAttribute('stroke-width','4');g.appendChild(r);const w=Math.abs(b.x-a.x)/20,h=Math.abs(b.y-a.y)/20;document.getElementById('geo-measure').textContent=`Genişlik ${w.toFixed(6)} · Yükseklik ${h.toFixed(6)} · Alan ${(w*h).toFixed(6)} birim²`}else if(tool==='circle'){const rpx=Math.hypot(b.x-a.x,b.y-a.y),r=rpx/20,c=document.createElementNS(ns,'circle');c.setAttribute('cx',a.x);c.setAttribute('cy',a.y);c.setAttribute('r',rpx);c.setAttribute('fill','none');c.setAttribute('stroke','#315ee7');c.setAttribute('stroke-width','4');g.appendChild(c);document.getElementById('geo-measure').textContent=`Yarıçap = ${r.toFixed(6)} · Çap = ${(2*r).toFixed(6)} · Çevre = ${(2*Math.PI*r).toFixed(6)} · Alan = ${(Math.PI*r*r).toFixed(6)}`}else if(tool==='ruler'){const len=Math.hypot(b.x-a.x,b.y-a.y)/20;document.getElementById('geo-measure').textContent=`Cetvel = ${len.toFixed(6)} birim`}else if(tool==='angle'){const mid=nearestPoint(a);const others=state.geo.points;if(others.length>=3){const C=others[others.length-1],B=others[others.length-2],A=others[others.length-3],deg=angleAt(A,B,C);document.getElementById('geo-measure').textContent=`Açı = ${deg.toFixed(6)}°`}}Api.event('geometri_araci')}
  function geoClear(){document.getElementById('geo-shapes').innerHTML='';state.geo.points=[];state.geo.start=null;document.getElementById('geo-measure').textContent='Bir araç seç.'}
  async function loadQuestions(){const g=document.getElementById('q-grade')?.value||'';const e=document.getElementById('math-questions');if(!e)return;e.innerHTML='Yükleniyor…';const j=await Api.questions(g);if(!j?.ok){e.textContent=j?.hata||'Sorular alınamadı.';return}e.innerHTML=(j.sorular||[]).slice(0,8).map(x=>`<div class="question-item"><b>${esc(x.baslik)}</b><span>${esc(x.yazar)} · ${esc(x.unite)} · ${x.cozuldu?'Çözüldü':'Açık'}</span><p>${esc(String(x.govde||'').slice(0,170))}</p></div>`).join('')||'<div class="mini-note">Henüz matematik sorusu yok.</div>'}
  async function askQuestion(){if(!state.user){location.href='../giris.html?donus=matematik/';return}const sinif=Number(document.getElementById('q-grade').value),unite=document.getElementById('q-topic').value,baslik=document.getElementById('q-title').value.trim(),govde=document.getElementById('q-body').value.trim();if(baslik.length<8||govde.length<10){document.getElementById('q-status').textContent='Başlık ve açıklama biraz daha detaylı olmalı.';return}const j=await Api.question({sinif,unite,baslik,govde});document.getElementById('q-status').textContent=j.ok?'Sorun ortak forumda yayınlandı.':(j.hata||'Yayınlanamadı.');if(j.ok){document.getElementById('q-title').value='';document.getElementById('q-body').value='';await Api.event('soru_paylasim');loadQuestions()}}
  async function refreshStats(){const j=await Api.stats().catch(()=>null);if(!j?.ok)return;const m=j.metrikler||{};const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=Number(v||0).toLocaleString('tr-TR')};set('math-stat-solve',m.hesap);set('math-stat-ai',m.ai);set('math-stat-q',m.soru);set('math-stat-geo',m.geometri);set('math-stat-pi',m.pi)}
  const MathMessages={
    init:async()=>{await loadSession();if(!state.user)return;await MathMessages.loadPeople()},
    loadPeople:async()=>{const e=document.getElementById('people');if(!e)return;const j=await Api.people();if(!j?.ok){e.textContent=j?.hata||'Kişiler alınamadı.';return}e.innerHTML=(j.kisiler||[]).map(x=>`<div class="person" onclick="MathMessages.open(${Number(x.id)})"><span class="avatar">${x.avatar?`<img class="avatar" src="${esc(x.avatar)}" alt="">`:esc(String(x.ad||'?')[0])}</span><span><b>${esc(x.ad)}</b><small>${esc(x.rol||'ogrenci')}</small></span></div>`).join('')||'<div class="mini-note">Başka kullanıcı yok.</div>'},
    open:async(id)=>{state.selectedPerson=id;const j=await Api.messages(id);if(!j?.ok){document.getElementById('chat-list').textContent=j?.hata||'Sohbet alınamadı.';return}document.getElementById('chat-head').textContent=j.karsi?.ad||'Sohbet';const me=state.user?.id;document.getElementById('chat-list').innerHTML=(j.mesajlar||[]).map(m=>`<div class="msg ${Number(m.gonderen_id)===Number(me)?'me':'them'}">${esc(m.metin)}</div>`).join('')||'<div class="empty-chat">Henüz mesaj yok.</div>'},
    send:async ev=>{ev.preventDefault();if(!state.selectedPerson)return;const input=document.getElementById('chat-input');const text=input.value.trim();if(!text)return;const j=await Api.sendMessage(state.selectedPerson,text);if(j.ok){input.value='';await MathMessages.open(state.selectedPerson)}}
  };
  const MathAdmin={init:async()=>{const j=await Api.call(CODES.matAdmin);if(!j?.ok){document.getElementById('adm-list').textContent=j?.hata||'Yetkisiz';return}const m=j.istatistik||{};const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=Number(v||0).toLocaleString('tr-TR')};set('adm-active',m.aktif);set('adm-ai',m.ai);set('adm-solves',m.hesap);set('adm-q',m.soru);set('adm-geo',m.geometri);set('adm-pi',m.pi);document.getElementById('adm-list').innerHTML=(j.son||[]).map(x=>`<div class="admin-row"><span>${esc(x.ad||'Kullanıcı')}</span><span>AI ${x.ai||0} · Hesap ${x.hesap||0}</span><span>Geo ${x.geometri||0}</span><span>${new Date(x.son_guncelleme).toLocaleString('tr-TR')}</span></div>`).join('')||'Henüz matematik aktivitesi yok.'},load:async function(){await this.init()}};
  window.MathApp={scrollTo,sinifSet,aiMode,analyzeImage,clearReader,copyResult,downloadAIImage,calculate,calcClear,piStart,copyPi,geoClear,askQuestion,loadQuestions,logout,appendCalc};
  window.MathMessages=MathMessages;window.MathAdmin=MathAdmin;
  document.addEventListener('DOMContentLoaded',init);
})();
